name: Three-Tier-App CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'assets/**'
      - 'terra-config/**'

jobs:
  # Job 1: Test the code
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4               # Loads a Fresh Ubuntu Machine

    - name: Set up Node.js
      uses: actions/setup-node@v4               # Downloads  Node Js Version 22
      with:
        node-version: '22'

    - name: Install and Test Backend
      run: |
        cd backend                                
        npm install                        # NPM install means downloads all dependencies from package.json
        npm test --if-present              # NPM test runs the test script if it exists and skip if it dosent without failing

    - name: Install and Test Frontend
      run: |
        cd frontend
        npm install
        CI=true npm test -- --passWithNoTests    # Prevent CI from failing if no React tests exist yet , Sets CI= True




  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR Public
      run: |
        aws ecr-public get-login-password --region us-east-1 | \
        docker login --username AWS --password-stdin public.ecr.aws

    - name: Build and Push Frontend
      uses: docker/build-push-action@v6
      with:
        context: ./frontend
        push: true
        tags: public.ecr.aws/l9q3x7d5/three-tier-frontend:${{ github.run_id }}

    - name: Build and Push Backend
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        push: true
        tags: public.ecr.aws/l9q3x7d5/three-tier-backend:${{ github.run_id }}
  
  



  update-k8s:
    runs-on: ubuntu-latest
    needs: push
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update Frontend image tag
      run: |
        sed -i 's|image: public.ecr.aws/l9q3x7d5/three-tier-frontend:.*|image: public.ecr.aws/l9q3x7d5/three-tier-frontend:${{ github.run_id }}|' k8s_manifests/frontend-deployment.yaml

    - name: Update Backend image tag
      run: |
        sed -i 's|image: public.ecr.aws/l9q3x7d5/three-tier-backend:.*|image: public.ecr.aws/l9q3x7d5/three-tier-backend:${{ github.run_id }}|' k8s_manifests/backend-deployment.yaml

    - name: Commit and push updated tags
      run: |
        git config --global user.email "rageworking1210@gmail.com"
        git config --global user.name "workinguser1012"
        git add k8s_manifests/frontend-deployment.yaml k8s_manifests/backend-deployment.yaml
        git commit -m "Update image tags to ${{ github.run_id }}"
        git push      