name: Three-Tier-App CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'assets/**'
      - 'terra-config/**'

jobs:
  # Job 1: Test the code
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install and Test Backend
      run: |
        cd backend
        npm install
        npm test --if-present

    - name: Install and Test Frontend
      run: |
        cd frontend
        npm install
        npm test --if-present

  